specs:
  dir: specs

jobs:
  dir: jobs

workingDirs:
  dir: wds

users:
  file: users

authentication:
  # Options: guest, basic, custom
  type: guest

jobManagement:
  maxRunningJobs: 10

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d{yy/MM/dd HH:mm:ss} %-5p %c: %m%n"